cameras:
  amcrest1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest4:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest5:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest6:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest7:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest8:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest9:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest10:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest11:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest12:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest13:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest14:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest15:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
  amcrest16:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://onvif:password!@192.168.0.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - record
detect:
  enabled: false

mqtt:
  enabled: false

record:
  enabled: true
  retain:
    days: 2
    mode: all
  events:
    retain:
      default: 10
      mode: motion

auth:
  enabled: false
  # reset_admin_password: true

tls:
  enabled: True # Optional: Enable TLS for port 8971

version: 0.14
